'''
Generated by Selenium IDE
Last modified: 3/28/2021 16:41
未完成項目：
1. 選擇車廂種類
'''
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import ElementNotInteractableException
import ticket_select

# 隱藏自動化測試標籤
option = webdriver.ChromeOptions()
option.add_experimental_option("excludeSwitches", ["enable-automation"])
option.add_experimental_option('useAutomationExtension', False)
option.add_argument('--disable-blink-features=AutomationControlled')
driver = webdriver.Chrome("./chromedriver", options=option)
# driver.execute_script('navigator.webdriver = null;')
first = True


def step1():
    # 台灣高鐵網址
    driver.get("https://irs.thsrc.com.tw/IMINT/?locale=tw")
    time.sleep(0.6)  # 這很重要，否則他會以為你是機器人

    global first
    if first:
        # 同意台灣高鐵網站使用 Cookie 分析和其他追蹤技術
        driver.find_element(By.NAME, "confirm").click()
        first = False

    # 選擇起程站
    # driver.find_element_by_name("selectStartStation").click()
    driver.find_element_by_xpath("//select[@name='selectStartStation']/option[text()='" + ticket_select.StartStation + "']").click()
    # 選擇到達站
    # driver.find_element_by_name("selectDestinationStation").click()
    driver.find_element_by_xpath("//select[@name='selectDestinationStation']/option[text()='" + ticket_select.DestinationStation + "']").click()

    # 選擇車廂種類 *暫時未完成*
    # driver.find_element(By.ID, ticket_select.car).click()

    # 選擇座位喜好
    driver.find_element(By.ID, ticket_select.PreferSeat).click()
    # 選擇直接輸入車次號碼
    driver.find_element(By.ID, "bookingMethod_1").click()
    # 輸入搭乘時間
    # driver.find_element_by_name("toTimeInputField").click()
    driver.execute_script("document.getElementsByName('toTimeInputField')[0].value = '" + ticket_select.Date + "'")
    driver.execute_script("document.getElementsByName('toTimeInputField')[0].onchange()")
    # driver.find_element_by_css_selector('[name="toTimeInputField"]').send_keys(ticket_select.Date)

    # 輸入全票人數
    # driver.find_element_by_name("ticketPanel:rows:0:ticketAmount").click()
    driver.find_element_by_xpath("//select[@name='ticketPanel:rows:0:ticketAmount']/option[text()='" + ticket_select.Adult_ticket + "']").click()
    # 輸入孩童票人數
    # driver.find_element_by_name("ticketPanel:rows:1:ticketAmount").click()
    driver.find_element_by_xpath("//select[@name='ticketPanel:rows:1:ticketAmount']/option[text()='" + ticket_select.Child_ticket + "']").click()
    # 輸入愛心票人數
    # driver.find_element_by_name("ticketPanel:rows:2:ticketAmount").click()
    driver.find_element_by_xpath("//select[@name='ticketPanel:rows:2:ticketAmount']/option[text()='" + ticket_select.Disabled_ticket + "']").click()
    # 輸入敬老票人數
    # driver.find_element_by_name("ticketPanel:rows:3:ticketAmount").click()
    driver.find_element_by_xpath("//select[@name='ticketPanel:rows:3:ticketAmount']/option[text()='" + ticket_select.Senior_ticket + "']").click()
    # 輸入大學生人數
    # driver.find_element_by_name("ticketPanel:rows:4:ticketAmount").click()
    driver.find_element_by_xpath("//select[@name='ticketPanel:rows:4:ticketAmount']/option[text()='" + ticket_select.College_ticket + "']").click()

    # 輸入車次號碼
    # driver.find_element(By.NAME, "toTrainIDInputField").click()
    driver.find_element(By.NAME, "toTrainIDInputField").send_keys(ticket_select.TrainNumber)
    # 在 terminal 輸入驗證碼後按下 Enter
    print("請輸入驗證碼：")
    verification = input()
    # driver.find_element(By.ID, "securityCode").click()
    driver.find_element(By.ID, "securityCode").send_keys(verification)
    # 確認
    driver.find_element(By.ID, "SubmitButton").click()


def step2():
    # 輸入取票人身分證字號
    driver.find_element(By.ID, "idNumber").send_keys(ticket_select.ID)
    # 輸入手機號碼
    driver.find_element(By.ID, "mobilePhone").send_keys(ticket_select.Phone)
    # 輸入電子郵件信箱
    driver.find_element(By.ID, "name2622").send_keys(ticket_select.E_mail)
    # 會員購票 (optional)
    driver.find_element(By.ID, "memberSystemCheckBox").click()
    # 同取票人身分證字號 (optional)
    driver.find_element(By.ID, "memberShipCheckBox").click()
    # 我已明確了解......
    driver.find_element(By.NAME, "agree").click()
    # 確定購票
    driver.find_element(By.ID, "isSubmit").click()
    # 再次確認會員帳號是否正確 (optional)
    input()
    driver.find_element(By.CSS_SELECTOR, "#dialog #btn-custom2").click()
    # 確定購票 (optional)
    driver.find_element(By.CSS_SELECTOR, ".table_simple tr:nth-child(1) > td:nth-child(1)").click()
    # 取得訂位代號
    number = driver.find_element_by_css_selector('[class="content_key"]').text
    print("訂位成功!!!")
    print("訂位代號：" + number)


while True:
    try:
        step1()
        step2()
        break
    except NoSuchElementException:
        driver.refresh()


input()
driver.quit()
